apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: azentia
type: Opaque

stringData:
  DB_HOST: azentia-db.cz2uiqs0cnc6.ap-south-1.rds.amazonaws.com
  DB_PORT: '5432'
  DB_USERNAME: postgres
  DB_PASSWORD: Aysha-chau
  DB_DATABASE: postgres

  SMTP_EMAIL: test@gmail.com
  SMTP_USER: test@gmail.com
  SMTP_PASSWORD: test123
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: '587'
