version: '3.8'

services:
  web:
    container_name: web

    build:
      context: .
      dockerfile: ./services/web/Dockerfile
      args:
        ENVIRONMENT: production
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_ENABLE_AI_CHAT: ${NEXT_PUBLIC_ENABLE_AI_CHAT}
        NEXT_PUBLIC_ENCRYPTION_KEY: ${NEXT_PUBLIC_ENCRYPTION_KEY}

    restart: always

    env_file:
      - .env

    environment:
      NODE_ENV: production
      WEB_PORT: 8081

    ports:
      - '8081:8081'

    networks:
      - azentia_network

    depends_on:
      - backend

  backend:
    container_name: backend

    build:
      context: .
      dockerfile: ./services/backend/Dockerfile

    restart: always

    env_file:
      - .env

    environment:
      NODE_ENV: production
      BACKEND_PORT: 1600

      FRONT_END_BASE_URL: ${FRONT_END_BASE_URL}

      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}

      TWILLIO_PASSWORD: ${TWILLIO_PASSWORD}
      TWILLIO_USER: ${TWILLIO_USER}

    ports:
      - '1600:1600'

    networks:
      - azentia_network

networks:
  azentia_network:
    driver: bridge
