export enum ENVIRONMENT_VARIABLES {
  NODE_ENV = 'NODE_ENV',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  EXPIRES_IN = '1d',
  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASSWORD = 'SUPER_ADMIN_PASSWORD',
}
