export enum ENVIRONMENT_VARIABLES {
  NODE_ENV = 'NODE_ENV',
  BACKEND_PORT = 'BACKEND_PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
}
