name: build app

on:
  push:
    branches:
      - master
  pull_request:

jobs:
    lint:
        name : lint and build app
        runs-on: ubuntu-latest
        steps:
          - name: Notify Google Chat
            id: 'notify_google_chat'
            uses: SimonScholz/google-chat-action@main
            with:
              webhookUrl: '${{ secrets.WEBHOOK_URL }}'
              jobStatus: ${{ job.status }}
              title: Meaning ful
              subtitle: Brought to you by Simon ;-)
          - name: checkout
            uses: actions/checkout@v4

          - name:  setup node
            uses: actions/setup-node@v4
            with:
                 node-version: 18.17.1

          - name: setup pnpm
            uses: pnpm/action-setup@v3

          - name: pnpm install
            run: pnpm install --frozen-lockfile

          - name : lint packages
            run: pnpm lint & pnpm format:check

          - name : build packages
            run : pnpm build