name: build app

on:
  push:
    branches:
      - master
  pull_request:

jobs:
    lint:
        name : lint and build app
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v4

          - name:  setup node
            uses: actions/setup-node@v4
            with:
                 node-version: 20

          - name: setup pnpm
            uses: pnpm/action-setup@v3

          - name: pnpm install
            run: pnpm install --frozen-lockfile

          - name : lint packages
            run: pnpm lint & pnpm format:check

          - name : build packages
            run : pnpm build