name: deplooy app

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment to deploy to'
        required: true
        default: 'qa'

jobs:
  create-shared-infra:
    name: create shared infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: ${{ github.event.inputs.environment }}
          OUTPUT_PATH: '.env' # optional

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: './'
          filenames: |
            .env

      - name: Terraform generate workspace
        run: |
          node ./scripts/start.js

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
  
      - name: Terraform Init
        id: init
        run: terraform -chdir=./terraform init
  
      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve -target=module.shared
  build:
    name: build and push docker images
    runs-on: ubuntu-latest
    needs:
      - create-shared-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  setup node
        uses: actions/setup-node@v4
        with:
            node-version: 18.17.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: ${{ github.event.inputs.environment }}
          OUTPUT_PATH: '.env' # optional

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: build docker images
        run: |
          docker-compose build

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: './'
          filenames: |
            .env

      - name: Generate version
        id: generate-version
        run: |
          node ./scripts/version.js
          echo "::set-output name=tag::VERSION_TAG"

      - name: List docker images
        run: |
          docker image ls

      - name: tag and push backend docker image
        id: push_backend_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: azentia-backend-image-repository
          TAG: ${{ steps.generate-version.outputs.tag }}
        run: |
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker tag azentia_backend:latest $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

      - name: tag and push web docker image
        id: push_web_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: azentia-web-image-repository
          TAG: ${{ steps.generate-version.outputs.tag }}
        run: |
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker tag azentia_web:latest $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"


      - name: Terraform generate workspace
        run: |
          source .env
          node ./scripts/start.js

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform -chdir=./terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=./terraform init

      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve

    # run-migrations:
    #   name: run db migrations
    #   runs-on: ubuntu-latest
    #   needs:
    #     - build
    #     - build_images_and_deploy
  
    #   steps:
    #     - name: Checkout
    #       uses: actions/checkout@v4
  
    #     - name:  setup node
    #       uses: actions/setup-node@v4
    #       with:
    #            node-version: 18.17.1
  
    #     - name: install dependencies & build packages
    #       run: |
    #         yarn sync
  
    #     - name: Store ENV from AWS SecretManager
    #       uses: say8425/aws-secrets-manager-actions@v2
    #       with:
    #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #         AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    #         SECRET_NAME: env/${{ github.event.inputs.environment }}
    #         OUTPUT_PATH: '.env' # optional
  
    #     - name: run migration
    #       run: |
    #         npm install -g lerna
    #         yarn migration:run