name: deplooy app

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment to deploy to'
        required: true
        default: 'qa'

jobs:
  create-shared-infra:
    name: create shared infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: ${{ github.event.inputs.environment }}
          OUTPUT_PATH: '.env' # optional

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: './'
          filenames: |
            .env

      - name: Generate provider 
        run: |
          node ./scripts/start.js

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '=1.6.6'

      - name: Terraform Workspace 
        id: workspace
        run: |
          terraform workspace new ${{ github.event.inputs.environment }}   

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
  
      - name: Terraform Init
        id: init
        run: terraform -chdir=./terraform init
  
      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve -target=module.shared
  build:
    name: build and push docker images + deploy
    runs-on: ubuntu-latest
    needs:
      - create-shared-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  setup node
        uses: actions/setup-node@v4
        with:
            node-version: 18.17.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: ${{ github.event.inputs.environment }}
          OUTPUT_PATH: '.env' # optional

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: build docker images
        run: |
          docker-compose build

      - name: Notify Google Chat
        id: 'notify_google_chat'
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.WEBHOOK_URL }}'
          title: Deploying
          subtitle: App might behave wierd

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: version
        run: node ./scripts/version.js

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: './'
          filenames: |
            .env

      - name: tag and push backend docker image
        id: push_backend_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: azentia-${{ github.event.inputs.environment }}-backend-image-repository
        run: |
          echo $VERSION_TAG
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          docker tag azentia_backend:latest $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG"

      - name: tag and push web docker image
        id: push_web_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: azentia-${{ github.event.inputs.environment }}-web-image-repository
        run: |
          echo $VERSION_TAG
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          docker tag azentia_web:latest $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG"


      - name: Generate provider 
        run: |
          node ./scripts/start.js

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '=1.6.6'

      - name: Terraform Workspace 
        id: workspace
        run: |
          terraform workspace new ${{ github.event.inputs.environment }}  

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform -chdir=./terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=./terraform init

      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve

      - name: create tag
        run: git tag $VERSION_TAG

      - name: push tag
        run: git push origin $VERSION_TAG

      - name: Notify Google Chat
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.WEBHOOK_URL }}'
          title: Deployment Finished
          subtitle: Use the app

  run-migrations:
    name: run db migrations
    runs-on: ubuntu-latest
    needs:
      - create-shared-infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  setup node
        uses: actions/setup-node@v4
        with:
              node-version: 18.17.1

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: ${{ github.event.inputs.environment }}
          OUTPUT_PATH: '.env' # optional

      - name : build packages
        run : pnpm build

      - name: show migrations
        run: |
          pnpm list-migrations

      - name: run migrations
        run: |
          pnpm migrate