name: run migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment to deploy to'
        required: true
        default: 'qa'

jobs:
  build:
    name: build and push docker images + deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  setup node
        uses: actions/setup-node@v4
        with:
            node-version: 18.17.1

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name : build packages
        run : pnpm build --scope=backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: ${{ github.event.inputs.environment }}
          OUTPUT_PATH: '.env' # optional

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: './'
          filenames: |
            .env

   
      - name: show migrations
        run: |
          pnpm list-migrations

      - name: run migrations
        run: |
          pnpm migrate
